import { readFileSync } from 'fs';
import { resolve } from 'path';

describe('note list structure', () => {
  test('노트 목록 page는 통계와 필터 렌더링을 전용 컴포넌트에 위임한다', () => {
    const source = readFileSync(resolve('app/note/_NoteContent.jsx'), 'utf8');
    const filterSource = readFileSync(resolve('app/note/_NoteFilterControls.jsx'), 'utf8');
    const statsSource = readFileSync(resolve('app/note/_NoteStatsSummary.jsx'), 'utf8');
    const cardGridSource = readFileSync(resolve('app/note/_NoteCardGrid.jsx'), 'utf8');
    const tableViewSource = readFileSync(resolve('app/note/_NoteTableView.jsx'), 'utf8');
    const headerSource = readFileSync(resolve('app/note/_NoteListHeader.jsx'), 'utf8');
    const statesSource = readFileSync(resolve('app/note/_NoteListStates.jsx'), 'utf8');
    const dialogsSource = readFileSync(resolve('app/note/_NotePageDialogs.jsx'), 'utf8');

    expect(source).toContain("import { NoteStatsSummary } from './_NoteStatsSummary'");
    expect(source).toContain("import { NoteFilterControls } from './_NoteFilterControls'");
    expect(source).toContain("import { NoteCardGrid } from './_NoteCardGrid'");
    expect(source).toContain("import { NoteTableView } from './_NoteTableView'");
    expect(source).toContain("import { NoteListHeader } from './_NoteListHeader'");
    expect(source).toContain("import { NoteListStates } from './_NoteListStates'");
    expect(source).toContain("import { NotePageDialogs } from './_NotePageDialogs'");
    expect(source).toContain('<NoteStatsSummary');
    expect(source).toContain('<NoteFilterControls');
    expect(source).toContain('<NoteCardGrid');
    expect(source).toContain('<NoteTableView');
    expect(source).toContain('<NoteListHeader');
    expect(source).toContain('<NoteListStates');
    expect(source).toContain('<NotePageDialogs');
    expect(source).not.toContain('const SORT_OPTIONS = [');
    expect(source).not.toContain("className={'chip' + (statusFilter === st ? ' active' : '')}");
    expect(source).not.toContain('className="stagger note-card-wrap"');
    expect(source).not.toContain('className="data-table stagger-rows"');
    expect(source).not.toContain('<PageHeader');
    expect(source).not.toContain('<ConfirmDialog');
    expect(source).not.toContain('<NoteCardSkeleton');
    expect(source).not.toContain('아직 노트가 없어요');
    expect(filterSource).toContain('const SORT_OPTIONS = [');
    expect(filterSource).toContain('제목, 메뉴명, 테스트 내용, 태그 검색');
    expect(statsSource).toContain('최근 6개월');
    expect(cardGridSource).toContain('export function NoteCardGrid');
    expect(cardGridSource).toContain('className="stagger note-card-wrap"');
    expect(tableViewSource).toContain('export function NoteTableView');
    expect(tableViewSource).toContain('className="data-table stagger-rows"');
    expect(headerSource).toContain('export function NoteListHeader');
    expect(headerSource).toContain('<PageHeader');
    expect(headerSource).toContain('<NoteBatchToolbar');
    expect(headerSource).toContain('보고예정 일괄복사');
    expect(statesSource).toContain('export function NoteListStates');
    expect(statesSource).toContain('<NoteCardSkeleton');
    expect(statesSource).toContain('아직 노트가 없어요');
    expect(statesSource).toContain('조건에 맞는 노트가 없어요');
    expect(dialogsSource).toContain('export function NotePageDialogs');
    expect(dialogsSource).toContain('<ConfirmDialog');
    expect(dialogsSource).toContain('프리셋을 삭제할까요?');
  });
});
