/**
 * 메뉴판매량 확장 분류 규칙 — 피자·1인피자 카테고리 (MS-9)
 *
 * 정책: MENU_SALES_DETAILED_POLICY.md "메뉴 그룹 매핑 규칙" 참조
 * 모든 pattern은 정규화 후 형식 (괄호 → 공백, 우괄호 제거).
 */

// 그룹 분류 참조 (문서용)
const PIZZA_GROUPS_4 = ['7번가스페셜', '새우파티', '흥부박포테이토']; // L,R,기본,피자
const PIZZA_GROUPS_3 = ['페스티벌']; // L,R,기본
const PIZZA_GROUPS_5_VARIANT = ['샘스테이크']; // L,R,기본,피자,변경
const PIZZA_GROUPS_5_FULL = [
  '체다골드포테이토',
  '고구마',
  '화이트쉬림프',
  '칠리크림불갈비',
  '불고기',
  '포테이토',
  '고르곤졸라',
  '체다파인애플',
  '컨츄리치킨',
]; // L,R,기본,피자,변경
const PIZZA_GROUPS_4_PEPE = ['페페로니']; // L,R,기본,변경,피자 (5개 - 페페로니 피자 포함)

function makePizzaRules(idStart) {
  const rules = [];
  let id = idStart;
  // 헬퍼: 6종 변형 패턴 생성 (선택 변형만 포함)
  return { rules, nextId: id };
}

export const MS9_RULES_PIZZA = [
  // ============================================================
  // 피자 카테고리 (103개)
  // 패턴: 정규화 후 (괄호 제거)
  // ============================================================

  // 7번가스페셜 (4)
  {
    ruleId: 'rule_pizza_010',
    name: '피자 - 7번가스페셜 L',
    pattern: '7번가스페셜 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '7번가스페셜',
    detailName: '7번가스페셜L',
  },
  {
    ruleId: 'rule_pizza_011',
    name: '피자 - 7번가스페셜 R',
    pattern: '7번가스페셜 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '7번가스페셜',
    detailName: '7번가스페셜R',
  },
  {
    ruleId: 'rule_pizza_012',
    name: '피자 - 7번가스페셜',
    pattern: '7번가스페셜',
    matchType: 'exact',
    category: '피자',
    groupName: '7번가스페셜',
    detailName: '7번가스페셜',
  },
  {
    ruleId: 'rule_pizza_013',
    name: '피자 - 7번가스페셜 피자',
    pattern: '7번가스페셜 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '7번가스페셜',
    detailName: '7번가스페셜',
  },

  // 샘스테이크 (5)
  {
    ruleId: 'rule_pizza_014',
    name: '피자 - 샘스테이크 L (피자)',
    pattern: '샘스테이크 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '샘스테이크',
    detailName: '샘스테이크L',
  },
  {
    ruleId: 'rule_pizza_015',
    name: '피자 - 샘스테이크 R (피자)',
    pattern: '샘스테이크 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '샘스테이크',
    detailName: '샘스테이크R',
  },
  {
    ruleId: 'rule_pizza_016',
    name: '피자 - 샘스테이크',
    pattern: '샘스테이크',
    matchType: 'exact',
    category: '피자',
    groupName: '샘스테이크',
    detailName: '샘스테이크',
  },
  {
    ruleId: 'rule_pizza_017',
    name: '피자 - 샘스테이크 피자',
    pattern: '샘스테이크 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '샘스테이크',
    detailName: '샘스테이크',
  },
  {
    ruleId: 'rule_pizza_018',
    name: '피자 - 샘스테이크 변경',
    pattern: '샘스테이크 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '샘스테이크',
    detailName: '샘스테이크',
  },

  // 체다골드포테이토 (5)
  {
    ruleId: 'rule_pizza_020',
    name: '피자 - 체다골드포테이토 L',
    pattern: '체다골드포테이토 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '체다골드포테이토',
    detailName: '체다골드포테이토L',
  },
  {
    ruleId: 'rule_pizza_021',
    name: '피자 - 체다골드포테이토 R',
    pattern: '체다골드포테이토 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '체다골드포테이토',
    detailName: '체다골드포테이토R',
  },
  {
    ruleId: 'rule_pizza_022',
    name: '피자 - 체다골드포테이토',
    pattern: '체다골드포테이토',
    matchType: 'exact',
    category: '피자',
    groupName: '체다골드포테이토',
    detailName: '체다골드포테이토',
  },
  {
    ruleId: 'rule_pizza_023',
    name: '피자 - 체다골드포테이토 피자',
    pattern: '체다골드포테이토 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '체다골드포테이토',
    detailName: '체다골드포테이토',
  },
  {
    ruleId: 'rule_pizza_024',
    name: '피자 - 체다골드포테이토 변경',
    pattern: '체다골드포테이토 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '체다골드포테이토',
    detailName: '체다골드포테이토',
  },

  // 새우파티 (4)
  {
    ruleId: 'rule_pizza_030',
    name: '피자 - 새우파티 L',
    pattern: '새우파티 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '새우파티',
    detailName: '새우파티L',
  },
  {
    ruleId: 'rule_pizza_031',
    name: '피자 - 새우파티 R',
    pattern: '새우파티 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '새우파티',
    detailName: '새우파티R',
  },
  {
    ruleId: 'rule_pizza_032',
    name: '피자 - 새우파티',
    pattern: '새우파티',
    matchType: 'exact',
    category: '피자',
    groupName: '새우파티',
    detailName: '새우파티',
  },
  {
    ruleId: 'rule_pizza_033',
    name: '피자 - 새우파티 피자',
    pattern: '새우파티 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '새우파티',
    detailName: '새우파티',
  },

  // 페스티벌 (3)
  {
    ruleId: 'rule_pizza_040',
    name: '피자 - 페스티벌 L',
    pattern: '페스티벌 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '페스티벌',
    detailName: '페스티벌L',
  },
  {
    ruleId: 'rule_pizza_041',
    name: '피자 - 페스티벌 R',
    pattern: '페스티벌 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '페스티벌',
    detailName: '페스티벌R',
  },
  {
    ruleId: 'rule_pizza_042',
    name: '피자 - 페스티벌',
    pattern: '페스티벌',
    matchType: 'exact',
    category: '피자',
    groupName: '페스티벌',
    detailName: '페스티벌',
  },

  // 고구마 (5)
  {
    ruleId: 'rule_pizza_050',
    name: '피자 - 고구마 L',
    pattern: '고구마 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '고구마',
    detailName: '고구마L',
  },
  {
    ruleId: 'rule_pizza_051',
    name: '피자 - 고구마 R',
    pattern: '고구마 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '고구마',
    detailName: '고구마R',
  },
  {
    ruleId: 'rule_pizza_052',
    name: '피자 - 고구마',
    pattern: '고구마',
    matchType: 'exact',
    category: '피자',
    groupName: '고구마',
    detailName: '고구마',
  },
  {
    ruleId: 'rule_pizza_053',
    name: '피자 - 고구마 피자',
    pattern: '고구마 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '고구마',
    detailName: '고구마',
  },
  {
    ruleId: 'rule_pizza_054',
    name: '피자 - 고구마 변경',
    pattern: '고구마 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '고구마',
    detailName: '고구마',
  },

  // 화이트쉬림프 (5)
  {
    ruleId: 'rule_pizza_060',
    name: '피자 - 화이트쉬림프 L',
    pattern: '화이트쉬림프 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '화이트쉬림프',
    detailName: '화이트쉬림프L',
  },
  {
    ruleId: 'rule_pizza_061',
    name: '피자 - 화이트쉬림프 R',
    pattern: '화이트쉬림프 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '화이트쉬림프',
    detailName: '화이트쉬림프R',
  },
  {
    ruleId: 'rule_pizza_062',
    name: '피자 - 화이트쉬림프',
    pattern: '화이트쉬림프',
    matchType: 'exact',
    category: '피자',
    groupName: '화이트쉬림프',
    detailName: '화이트쉬림프',
  },
  {
    ruleId: 'rule_pizza_063',
    name: '피자 - 화이트쉬림프 피자',
    pattern: '화이트쉬림프 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '화이트쉬림프',
    detailName: '화이트쉬림프',
  },
  {
    ruleId: 'rule_pizza_064',
    name: '피자 - 화이트쉬림프 변경',
    pattern: '화이트쉬림프 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '화이트쉬림프',
    detailName: '화이트쉬림프',
  },

  // 칠리크림불갈비 (5)
  {
    ruleId: 'rule_pizza_070',
    name: '피자 - 칠리크림불갈비 L',
    pattern: '칠리크림불갈비 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '칠리크림불갈비',
    detailName: '칠리크림불갈비L',
  },
  {
    ruleId: 'rule_pizza_071',
    name: '피자 - 칠리크림불갈비 R',
    pattern: '칠리크림불갈비 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '칠리크림불갈비',
    detailName: '칠리크림불갈비R',
  },
  {
    ruleId: 'rule_pizza_072',
    name: '피자 - 칠리크림불갈비',
    pattern: '칠리크림불갈비',
    matchType: 'exact',
    category: '피자',
    groupName: '칠리크림불갈비',
    detailName: '칠리크림불갈비',
  },
  {
    ruleId: 'rule_pizza_073',
    name: '피자 - 칠리크림불갈비 피자',
    pattern: '칠리크림불갈비 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '칠리크림불갈비',
    detailName: '칠리크림불갈비',
  },
  {
    ruleId: 'rule_pizza_074',
    name: '피자 - 칠리크림불갈비 변경',
    pattern: '칠리크림불갈비 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '칠리크림불갈비',
    detailName: '칠리크림불갈비',
  },

  // 레드핫그릴치킨 (5, BASIC_RULES rule_pizza_002가 "레드핫그릴치킨" 단독 담당)
  {
    ruleId: 'rule_pizza_080',
    name: '피자 - 레드핫그릴치킨 L',
    pattern: '레드핫그릴치킨 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '레드핫그릴치킨',
    detailName: '레드핫그릴치킨L',
  },
  {
    ruleId: 'rule_pizza_081',
    name: '피자 - 레드핫그릴치킨 R',
    pattern: '레드핫그릴치킨 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '레드핫그릴치킨',
    detailName: '레드핫그릴치킨R',
  },
  {
    ruleId: 'rule_pizza_082',
    name: '피자 - 레드핫그릴치킨 변경',
    pattern: '레드핫그릴치킨 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '레드핫그릴치킨',
    detailName: '레드핫그릴치킨',
  },
  {
    ruleId: 'rule_pizza_083',
    name: '피자 - 레드핫그릴 변경 (축약)',
    pattern: '레드핫그릴 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '레드핫그릴치킨',
    detailName: '레드핫그릴치킨',
  },
  {
    ruleId: 'rule_pizza_084',
    name: '피자 - 레드핫그릴 피자 (축약)',
    pattern: '레드핫그릴 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '레드핫그릴치킨',
    detailName: '레드핫그릴치킨',
  },

  // 흥부박포테이토 (4)
  {
    ruleId: 'rule_pizza_090',
    name: '피자 - 흥부박포테이토 L',
    pattern: '흥부박포테이토 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '흥부박포테이토',
    detailName: '흥부박포테이토L',
  },
  {
    ruleId: 'rule_pizza_091',
    name: '피자 - 흥부박포테이토 R',
    pattern: '흥부박포테이토 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '흥부박포테이토',
    detailName: '흥부박포테이토R',
  },
  {
    ruleId: 'rule_pizza_092',
    name: '피자 - 흥부박포테이토',
    pattern: '흥부박포테이토',
    matchType: 'exact',
    category: '피자',
    groupName: '흥부박포테이토',
    detailName: '흥부박포테이토',
  },
  {
    ruleId: 'rule_pizza_093',
    name: '피자 - 흥부박포테이토 피자',
    pattern: '흥부박포테이토 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '흥부박포테이토',
    detailName: '흥부박포테이토',
  },

  // 페페로니 (5, 페페로니 피자 포함)
  {
    ruleId: 'rule_pizza_100',
    name: '피자 - 페페로니 L',
    pattern: '페페로니 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '페페로니',
    detailName: '페페로니L',
  },
  {
    ruleId: 'rule_pizza_101',
    name: '피자 - 페페로니 R',
    pattern: '페페로니 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '페페로니',
    detailName: '페페로니R',
  },
  {
    ruleId: 'rule_pizza_102',
    name: '피자 - 페페로니',
    pattern: '페페로니',
    matchType: 'exact',
    category: '피자',
    groupName: '페페로니',
    detailName: '페페로니',
  },
  {
    ruleId: 'rule_pizza_103',
    name: '피자 - 페페로니 변경',
    pattern: '페페로니 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '페페로니',
    detailName: '페페로니',
  },
  {
    ruleId: 'rule_pizza_104',
    name: '피자 - 페페로니 피자',
    pattern: '페페로니 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '페페로니',
    detailName: '페페로니',
  },

  // 슈퍼콤비네이션 (5)
  {
    ruleId: 'rule_pizza_110',
    name: '피자 - 슈퍼콤비네이션 L',
    pattern: '슈퍼콤비네이션 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '슈퍼콤비네이션',
    detailName: '슈퍼콤비네이션L',
  },
  {
    ruleId: 'rule_pizza_111',
    name: '피자 - 슈퍼콤비네이션 R',
    pattern: '슈퍼콤비네이션 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '슈퍼콤비네이션',
    detailName: '슈퍼콤비네이션R',
  },
  {
    ruleId: 'rule_pizza_112',
    name: '피자 - 슈퍼콤비네이션',
    pattern: '슈퍼콤비네이션',
    matchType: 'exact',
    category: '피자',
    groupName: '슈퍼콤비네이션',
    detailName: '슈퍼콤비네이션',
  },
  {
    ruleId: 'rule_pizza_113',
    name: '피자 - 슈퍼콤비네이션 피자',
    pattern: '슈퍼콤비네이션 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '슈퍼콤비네이션',
    detailName: '슈퍼콤비네이션',
  },
  {
    ruleId: 'rule_pizza_114',
    name: '피자 - 슈퍼콤비네이션 선택',
    pattern: '슈퍼콤비네이션 선택',
    matchType: 'exact',
    category: '피자',
    groupName: '슈퍼콤비네이션',
    detailName: '슈퍼콤비네이션',
  },

  // 불고기 (5)
  {
    ruleId: 'rule_pizza_120',
    name: '피자 - 불고기 L',
    pattern: '불고기 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '불고기',
    detailName: '불고기L',
  },
  {
    ruleId: 'rule_pizza_121',
    name: '피자 - 불고기 R',
    pattern: '불고기 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '불고기',
    detailName: '불고기R',
  },
  {
    ruleId: 'rule_pizza_122',
    name: '피자 - 불고기',
    pattern: '불고기',
    matchType: 'exact',
    category: '피자',
    groupName: '불고기',
    detailName: '불고기',
  },
  {
    ruleId: 'rule_pizza_123',
    name: '피자 - 불고기 피자',
    pattern: '불고기 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '불고기',
    detailName: '불고기',
  },
  {
    ruleId: 'rule_pizza_124',
    name: '피자 - 불고기 변경',
    pattern: '불고기 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '불고기',
    detailName: '불고기',
  },

  // 뉴더블치즈 (5, BASIC_RULES rule_pizza_001은 "뉴더블치즈피자" 단독)
  {
    ruleId: 'rule_pizza_130',
    name: '피자 - 뉴더블치즈 L',
    pattern: '뉴더블치즈 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '뉴더블치즈',
    detailName: '뉴더블치즈L',
  },
  {
    ruleId: 'rule_pizza_131',
    name: '피자 - 뉴더블치즈 R',
    pattern: '뉴더블치즈 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '뉴더블치즈',
    detailName: '뉴더블치즈R',
  },
  {
    ruleId: 'rule_pizza_132',
    name: '피자 - 뉴더블치즈',
    pattern: '뉴더블치즈',
    matchType: 'exact',
    category: '피자',
    groupName: '뉴더블치즈',
    detailName: '뉴더블치즈',
  },
  {
    ruleId: 'rule_pizza_133',
    name: '피자 - 뉴더블치즈 변경',
    pattern: '뉴더블치즈 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '뉴더블치즈',
    detailName: '뉴더블치즈',
  },
  {
    ruleId: 'rule_pizza_134',
    name: '피자 - 뉴더블 L (축약)',
    pattern: '뉴더블 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '뉴더블치즈',
    detailName: '뉴더블치즈L',
  },

  // 포테이토 (5)
  {
    ruleId: 'rule_pizza_140',
    name: '피자 - 포테이토 L',
    pattern: '포테이토 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '포테이토',
    detailName: '포테이토L',
  },
  {
    ruleId: 'rule_pizza_141',
    name: '피자 - 포테이토 R',
    pattern: '포테이토 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '포테이토',
    detailName: '포테이토R',
  },
  {
    ruleId: 'rule_pizza_142',
    name: '피자 - 포테이토',
    pattern: '포테이토',
    matchType: 'exact',
    category: '피자',
    groupName: '포테이토',
    detailName: '포테이토',
  },
  {
    ruleId: 'rule_pizza_143',
    name: '피자 - 포테이토 피자',
    pattern: '포테이토 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '포테이토',
    detailName: '포테이토',
  },
  {
    ruleId: 'rule_pizza_144',
    name: '피자 - 포테이토 변경',
    pattern: '포테이토 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '포테이토',
    detailName: '포테이토',
  },

  // 고르곤졸라 (5)
  {
    ruleId: 'rule_pizza_150',
    name: '피자 - 고르곤졸라 L',
    pattern: '고르곤졸라 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '고르곤졸라',
    detailName: '고르곤졸라L',
  },
  {
    ruleId: 'rule_pizza_151',
    name: '피자 - 고르곤졸라 R',
    pattern: '고르곤졸라 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '고르곤졸라',
    detailName: '고르곤졸라R',
  },
  {
    ruleId: 'rule_pizza_152',
    name: '피자 - 고르곤졸라',
    pattern: '고르곤졸라',
    matchType: 'exact',
    category: '피자',
    groupName: '고르곤졸라',
    detailName: '고르곤졸라',
  },
  {
    ruleId: 'rule_pizza_153',
    name: '피자 - 고르곤졸라 피자',
    pattern: '고르곤졸라 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '고르곤졸라',
    detailName: '고르곤졸라',
  },
  {
    ruleId: 'rule_pizza_154',
    name: '피자 - 고르곤졸라 변경',
    pattern: '고르곤졸라 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '고르곤졸라',
    detailName: '고르곤졸라',
  },

  // 체다파인애플 (5)
  {
    ruleId: 'rule_pizza_160',
    name: '피자 - 체다파인애플 L',
    pattern: '체다파인애플 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '체다파인애플',
    detailName: '체다파인애플L',
  },
  {
    ruleId: 'rule_pizza_161',
    name: '피자 - 체다파인애플 R',
    pattern: '체다파인애플 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '체다파인애플',
    detailName: '체다파인애플R',
  },
  {
    ruleId: 'rule_pizza_162',
    name: '피자 - 체다파인애플',
    pattern: '체다파인애플',
    matchType: 'exact',
    category: '피자',
    groupName: '체다파인애플',
    detailName: '체다파인애플',
  },
  {
    ruleId: 'rule_pizza_163',
    name: '피자 - 체다파인애플 피자',
    pattern: '체다파인애플 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '체다파인애플',
    detailName: '체다파인애플',
  },
  {
    ruleId: 'rule_pizza_164',
    name: '피자 - 체다파인애플 변경',
    pattern: '체다파인애플 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '체다파인애플',
    detailName: '체다파인애플',
  },

  // 컨츄리치킨 (5)
  {
    ruleId: 'rule_pizza_170',
    name: '피자 - 컨츄리치킨 L',
    pattern: '컨츄리치킨 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '컨츄리치킨',
    detailName: '컨츄리치킨L',
  },
  {
    ruleId: 'rule_pizza_171',
    name: '피자 - 컨츄리치킨 R',
    pattern: '컨츄리치킨 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '컨츄리치킨',
    detailName: '컨츄리치킨R',
  },
  {
    ruleId: 'rule_pizza_172',
    name: '피자 - 컨츄리치킨',
    pattern: '컨츄리치킨',
    matchType: 'exact',
    category: '피자',
    groupName: '컨츄리치킨',
    detailName: '컨츄리치킨',
  },
  {
    ruleId: 'rule_pizza_173',
    name: '피자 - 컨츄리치킨 피자',
    pattern: '컨츄리치킨 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '컨츄리치킨',
    detailName: '컨츄리치킨',
  },
  {
    ruleId: 'rule_pizza_174',
    name: '피자 - 컨츄리치킨 변경',
    pattern: '컨츄리치킨 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '컨츄리치킨',
    detailName: '컨츄리치킨',
  },

  // 고추장불고기 (12, 메뉴명 변경: 고추장버터불고기 → 고추장불고기, 양쪽 6개씩)
  // 구메뉴명
  {
    ruleId: 'rule_pizza_180',
    name: '피자 - 고추장버터불고기 L (구)',
    pattern: '고추장버터불고기 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기L',
  },
  {
    ruleId: 'rule_pizza_181',
    name: '피자 - 고추장버터불고기 R (구)',
    pattern: '고추장버터불고기 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기R',
  },
  {
    ruleId: 'rule_pizza_182',
    name: '피자 - 고추장버터불고기 (구)',
    pattern: '고추장버터불고기',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },
  {
    ruleId: 'rule_pizza_183',
    name: '피자 - 고추장버터불고기 피자 (구)',
    pattern: '고추장버터불고기 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },
  {
    ruleId: 'rule_pizza_184',
    name: '피자 - 고추장버터불고기 변경 (구)',
    pattern: '고추장버터불고기 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },
  {
    ruleId: 'rule_pizza_185',
    name: '피자 - 고추장버터불고기 추가 (구)',
    pattern: '고추장버터불고기 추가',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },
  // 신메뉴명
  {
    ruleId: 'rule_pizza_186',
    name: '피자 - 고추장불고기 L',
    pattern: '고추장불고기 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기L',
  },
  {
    ruleId: 'rule_pizza_187',
    name: '피자 - 고추장불고기 R',
    pattern: '고추장불고기 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기R',
  },
  {
    ruleId: 'rule_pizza_188',
    name: '피자 - 고추장불고기',
    pattern: '고추장불고기',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },
  {
    ruleId: 'rule_pizza_189',
    name: '피자 - 고추장불고기 피자',
    pattern: '고추장불고기 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },
  {
    ruleId: 'rule_pizza_190',
    name: '피자 - 고추장불고기 변경',
    pattern: '고추장불고기 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },
  {
    ruleId: 'rule_pizza_191',
    name: '피자 - 고추장불고기 추가',
    pattern: '고추장불고기 추가',
    matchType: 'exact',
    category: '피자',
    groupName: '고추장불고기',
    detailName: '고추장불고기',
  },

  // 까망베르더블치즈 (6, 신메뉴 사전 등록)
  {
    ruleId: 'rule_pizza_200',
    name: '피자 - 까망베르더블치즈 L',
    pattern: '까망베르더블치즈 피자 L',
    matchType: 'exact',
    category: '피자',
    groupName: '까망베르더블치즈',
    detailName: '까망베르더블치즈L',
  },
  {
    ruleId: 'rule_pizza_201',
    name: '피자 - 까망베르더블치즈 R',
    pattern: '까망베르더블치즈 피자 R',
    matchType: 'exact',
    category: '피자',
    groupName: '까망베르더블치즈',
    detailName: '까망베르더블치즈R',
  },
  {
    ruleId: 'rule_pizza_202',
    name: '피자 - 까망베르더블치즈',
    pattern: '까망베르더블치즈',
    matchType: 'exact',
    category: '피자',
    groupName: '까망베르더블치즈',
    detailName: '까망베르더블치즈',
  },
  {
    ruleId: 'rule_pizza_203',
    name: '피자 - 까망베르더블치즈 피자',
    pattern: '까망베르더블치즈 피자',
    matchType: 'exact',
    category: '피자',
    groupName: '까망베르더블치즈',
    detailName: '까망베르더블치즈',
  },
  {
    ruleId: 'rule_pizza_204',
    name: '피자 - 까망베르더블치즈 변경',
    pattern: '까망베르더블치즈 변경',
    matchType: 'exact',
    category: '피자',
    groupName: '까망베르더블치즈',
    detailName: '까망베르더블치즈',
  },
  {
    ruleId: 'rule_pizza_205',
    name: '피자 - 까망베르더블치즈 추가',
    pattern: '까망베르더블치즈 추가',
    matchType: 'exact',
    category: '피자',
    groupName: '까망베르더블치즈',
    detailName: '까망베르더블치즈',
  },

  // ============================================================
  // 1인피자 카테고리 (11개, BASIC_RULES rule_personal_001 "더블치즈" 별도)
  // 페페로니/고르곤졸라는 피자 카테고리와 groupName 충돌 회피 위해 "(P)" 접미사 사용
  // ============================================================
  {
    ruleId: 'rule_personal_002',
    name: '1인피자 - 페페로니 P',
    pattern: '페페로니 피자 P',
    matchType: 'exact',
    category: '1인피자',
    groupName: '페페로니(P)',
    detailName: '페페로니(P)',
  },
  {
    ruleId: 'rule_personal_003',
    name: '1인피자 - 페페로니 P 추가',
    pattern: '페페로니 피자 P 추가',
    matchType: 'exact',
    category: '1인피자',
    groupName: '페페로니(P)',
    detailName: '페페로니(P)',
  },
  {
    ruleId: 'rule_personal_004',
    name: '1인피자 - 고르곤졸라 P',
    pattern: '고르곤졸라 피자 P',
    matchType: 'exact',
    category: '1인피자',
    groupName: '고르곤졸라(P)',
    detailName: '고르곤졸라(P)',
  },
  {
    ruleId: 'rule_personal_005',
    name: '1인피자 - 하와이안 P',
    pattern: '하와이안 피자 P',
    matchType: 'exact',
    category: '1인피자',
    groupName: '하와이안',
    detailName: '하와이안',
  },
  {
    ruleId: 'rule_personal_006',
    name: '1인피자 - 하와이안 P 추가',
    pattern: '하와이안 피자 P 추가',
    matchType: 'exact',
    category: '1인피자',
    groupName: '하와이안',
    detailName: '하와이안',
  },
  {
    ruleId: 'rule_personal_007',
    name: '1인피자 - 하와이안 피자',
    pattern: '하와이안 피자',
    matchType: 'exact',
    category: '1인피자',
    groupName: '하와이안',
    detailName: '하와이안',
  },
  {
    ruleId: 'rule_personal_008',
    name: '1인피자 - 더블치즈 P',
    pattern: '더블치즈 피자 P',
    matchType: 'exact',
    category: '1인피자',
    groupName: '더블치즈',
    detailName: '더블치즈',
  },
  {
    ruleId: 'rule_personal_009',
    name: '1인피자 - 더블치즈 피자',
    pattern: '더블치즈 피자',
    matchType: 'exact',
    category: '1인피자',
    groupName: '더블치즈',
    detailName: '더블치즈',
  },
  {
    ruleId: 'rule_personal_010',
    name: '1인피자 - 콤보치즈 P',
    pattern: '콤보치즈 피자 P',
    matchType: 'exact',
    category: '1인피자',
    groupName: '콤보치즈',
    detailName: '콤보치즈',
  },
  {
    ruleId: 'rule_personal_011',
    name: '1인피자 - 콤보치즈 P 추가',
    pattern: '콤보치즈 피자 P 추가',
    matchType: 'exact',
    category: '1인피자',
    groupName: '콤보치즈',
    detailName: '콤보치즈',
  },
  {
    ruleId: 'rule_personal_012',
    name: '1인피자 - 콤보치즈 피자',
    pattern: '콤보치즈 피자',
    matchType: 'exact',
    category: '1인피자',
    groupName: '콤보치즈',
    detailName: '콤보치즈',
  },
];
