/**
 * 메뉴판매량 확장 분류 규칙 — 사이드·소스·추가토핑·음료·품목제외 카테고리 (MS-9)
 *
 * 정책: MENU_SALES_DETAILED_POLICY.md "메뉴 그룹 매핑 규칙" 참조
 */

export const MS9_RULES_SIDE = [
  // ============================================================
  // 사이드 카테고리 (26개) — 기존 적용
  // ============================================================

  // 오븐스파게티 그룹 (3개, BASIC_RULES rule_side_001이 "오븐스파게티" 단독 담당)
  {
    ruleId: 'rule_side_002',
    name: '사이드 - 오븐스파게티 선택',
    pattern: '오븐스파게티 선택',
    matchType: 'exact',
    category: '사이드',
    groupName: '오븐스파게티',
    detailName: '오븐스파게티',
  },
  {
    ruleId: 'rule_side_003',
    name: '사이드 - 오븐스파게티 변경',
    pattern: '오븐스파게티 변경',
    matchType: 'exact',
    category: '사이드',
    groupName: '오븐스파게티',
    detailName: '오븐스파게티',
  },
  {
    ruleId: 'rule_side_004',
    name: '사이드 - 오븐스파게티 추가',
    pattern: '오븐스파게티 추가',
    matchType: 'exact',
    category: '사이드',
    groupName: '오븐스파게티',
    detailName: '오븐스파게티',
  },

  // 로제스파게티 그룹 (3개)
  {
    ruleId: 'rule_side_005',
    name: '사이드 - 로제 스파게티',
    pattern: '로제 스파게티',
    matchType: 'exact',
    category: '사이드',
    groupName: '로제스파게티',
    detailName: '로제스파게티',
  },
  {
    ruleId: 'rule_side_006',
    name: '사이드 - 로제스파게티 변경',
    pattern: '로제스파게티 변경',
    matchType: 'exact',
    category: '사이드',
    groupName: '로제스파게티',
    detailName: '로제스파게티',
  },
  {
    ruleId: 'rule_side_007',
    name: '사이드 - 로제스파게티 선택',
    pattern: '로제스파게티 선택',
    matchType: 'exact',
    category: '사이드',
    groupName: '로제스파게티',
    detailName: '로제스파게티',
  },

  // 핫윙 그룹 (3개, 콘코울슬로 콤보는 classify 단계에서 콘코울슬로 그룹에 자동 추가됨)
  {
    ruleId: 'rule_side_008',
    name: '사이드 - 핫윙 4PCS',
    pattern: '핫윙 4PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '핫윙',
    detailName: '핫윙4pcs',
  },
  {
    ruleId: 'rule_side_009',
    name: '사이드 - 핫윙 20PCS',
    pattern: '핫윙 20PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '핫윙',
    detailName: '핫윙20pcs',
  },
  {
    ruleId: 'rule_side_010',
    name: '세트 - 핫윙 4PCS+콘코울슬로',
    pattern: '핫윙 4PCS+콘코울슬로',
    matchType: 'exact',
    category: '세트메뉴',
    groupName: '사이드+콘코울슬로',
    detailName: '핫윙4PCS+콘코울슬로',
  },

  // 치킨바사삭 그룹 (6개)
  {
    ruleId: 'rule_side_011',
    name: '사이드 - 치킨 바사삭 12PCS',
    pattern: '치킨 바사삭 12PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '치킨바사삭',
    detailName: '치킨바사삭12pcs',
  },
  {
    ruleId: 'rule_side_012',
    name: '사이드 - 치킨 바사삭 6PCS',
    pattern: '치킨 바사삭 6PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '치킨바사삭',
    detailName: '치킨바사삭6pcs',
  },
  {
    ruleId: 'rule_side_013',
    name: '세트 - 치킨 바사삭 6PCS+콘코울슬로',
    pattern: '치킨 바사삭 6PCS+콘코울슬로',
    matchType: 'exact',
    category: '세트메뉴',
    groupName: '사이드+콘코울슬로',
    detailName: '치킨바사삭6PCS+콘코울슬로',
  },
  {
    ruleId: 'rule_side_014',
    name: '세트 - 치킨 바사삭 12PCS+콘코울슬로',
    pattern: '치킨 바사삭 12PCS+콘코울슬로',
    matchType: 'exact',
    category: '세트메뉴',
    groupName: '사이드+콘코울슬로',
    detailName: '치킨바사삭12PCS+콘코울슬로',
  },
  {
    ruleId: 'rule_side_015',
    name: '사이드 - 치킨 바사삭 12PCS 변경',
    pattern: '치킨 바사삭 12PCS 변경',
    matchType: 'exact',
    category: '사이드',
    groupName: '치킨바사삭',
    detailName: '치킨바사삭',
  },
  {
    ruleId: 'rule_side_016',
    name: '사이드 - 치킨 바사삭 6PCS 선택',
    pattern: '치킨 바사삭 6PCS 선택',
    matchType: 'exact',
    category: '사이드',
    groupName: '치킨바사삭',
    detailName: '치킨바사삭',
  },

  // 떡볶이 단일 그룹 (3개)
  {
    ruleId: 'rule_side_017',
    name: '사이드 - 오븐치즈 떡볶이',
    pattern: '오븐치즈 떡볶이',
    matchType: 'exact',
    category: '사이드',
    groupName: '오븐치즈떡볶이',
    detailName: '오븐치즈떡볶이',
  },
  {
    ruleId: 'rule_side_018',
    name: '사이드 - 페페로니 떡볶이',
    pattern: '페페로니 떡볶이',
    matchType: 'exact',
    category: '사이드',
    groupName: '페페로니떡볶이',
    detailName: '페페로니떡볶이',
  },
  {
    ruleId: 'rule_side_019',
    name: '사이드 - 체다골드포테이토 떡볶이',
    pattern: '체다골드포테이토 떡볶이',
    matchType: 'exact',
    category: '사이드',
    groupName: '체다골드포테이토떡볶이',
    detailName: '체다골드포테이토떡볶이',
  },

  // 단일 PCS 메뉴 (6개)
  {
    ruleId: 'rule_side_020',
    name: '사이드 - 그릴 닭다리살 3PCS',
    pattern: '그릴 닭다리살 3PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '그릴닭다리살',
    detailName: '그릴닭다리살3pcs',
  },
  {
    ruleId: 'rule_side_021',
    name: '사이드 - 흑미크림 찰치즈볼 5PCS',
    pattern: '흑미크림 찰치즈볼 5PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '흑미크림찰치즈볼',
    detailName: '흑미크림찰치즈볼5pcs',
  },
  {
    ruleId: 'rule_side_022',
    name: '사이드 - 케이준 치킨텐더 5PCS',
    pattern: '케이준 치킨텐더 5PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '케이준치킨텐더',
    detailName: '케이준치킨텐더5pcs',
  },
  {
    ruleId: 'rule_side_023',
    name: '사이드 - 통통 새우링 4PCS',
    pattern: '통통 새우링 4PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '통통새우링',
    detailName: '통통새우링4pcs',
  },
  {
    ruleId: 'rule_side_024',
    name: '사이드 - 롱츄러스 4PCS',
    pattern: '롱츄러스 4PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '롱츄러스',
    detailName: '롱츄러스4pcs',
  },
  {
    ruleId: 'rule_side_025',
    name: '사이드 - 골드 멘보샤 3PCS',
    pattern: '골드 멘보샤 3PCS',
    matchType: 'exact',
    category: '사이드',
    groupName: '골드멘보샤',
    detailName: '골드멘보샤3pcs',
  },

  // 단일 기타 메뉴 (3개)
  {
    ruleId: 'rule_side_026',
    name: '사이드 - 콘코울슬로',
    pattern: '콘코울슬로',
    matchType: 'exact',
    category: '사이드',
    groupName: '콘코울슬로',
    detailName: '콘코울슬로',
  },
  {
    ruleId: 'rule_side_027',
    name: '사이드 - 감자튀김',
    pattern: '감자튀김',
    matchType: 'exact',
    category: '사이드',
    groupName: '감자튀김',
    detailName: '감자튀김',
  },
  {
    ruleId: 'rule_side_028',
    name: '사이드 - 쉬림프아라비아따',
    pattern: '쉬림프아라비아따',
    matchType: 'exact',
    category: '사이드',
    groupName: '쉬림프아라비아따',
    detailName: '쉬림프아라비아따',
  },

  // ============================================================
  // 사이드(소스) 카테고리 (8개, BASIC_RULES rule_sauce_001 "파마산" 단독)
  // 파마산 그룹은 치즈가루/파마산 추가 통합
  // ============================================================
  {
    ruleId: 'rule_sauce_002',
    name: '사이드(소스) - 치즈가루 (파마산 통합)',
    pattern: '치즈가루',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '파마산',
    detailName: '파마산',
  },
  {
    ruleId: 'rule_sauce_003',
    name: '사이드(소스) - 파마산 추가 (파마산 통합)',
    pattern: '파마산 추가',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '파마산',
    detailName: '파마산',
  },
  {
    ruleId: 'rule_sauce_004',
    name: '사이드(소스) - 피클',
    pattern: '피클',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '피클',
    detailName: '피클',
  },
  {
    ruleId: 'rule_sauce_005',
    name: '사이드(소스) - 갈릭디핑소스',
    pattern: '갈릭디핑소스',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '갈릭디핑소스',
    detailName: '갈릭디핑소스',
  },
  {
    ruleId: 'rule_sauce_006',
    name: '사이드(소스) - 할라피뇨쨈',
    pattern: '할라피뇨쨈',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '할라피뇨쨈',
    detailName: '할라피뇨쨈',
  },
  {
    ruleId: 'rule_sauce_007',
    name: '사이드(소스) - 핫소스',
    pattern: '핫소스',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '핫소스',
    detailName: '핫소스',
  },
  {
    ruleId: 'rule_sauce_008',
    name: '사이드(소스) - 꿀',
    pattern: '꿀',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '꿀',
    detailName: '꿀',
  },
  {
    ruleId: 'rule_sauce_009',
    name: '사이드(소스) - 스위트칠리소스',
    pattern: '스위트칠리소스',
    matchType: 'exact',
    category: '사이드(소스)',
    groupName: '스위트칠리소스',
    detailName: '스위트칠리소스',
  },

  // ============================================================
  // 추가토핑 카테고리 (21개)
  // 각 토핑은 독립 그룹. groupName은 "{토핑명} 추가" 형식
  // ============================================================
  {
    ruleId: 'rule_topping_001',
    name: '추가토핑 - 치즈 추가',
    pattern: '치즈 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '치즈 추가',
    detailName: '치즈 추가',
  },
  {
    ruleId: 'rule_topping_002',
    name: '추가토핑 - 파인애플 추가',
    pattern: '파인애플 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '파인애플 추가',
    detailName: '파인애플 추가',
  },
  {
    ruleId: 'rule_topping_003',
    name: '추가토핑 - 페페로니 추가',
    pattern: '페페로니 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '페페로니 추가',
    detailName: '페페로니 추가',
  },
  {
    ruleId: 'rule_topping_004',
    name: '추가토핑 - 베이컨 추가',
    pattern: '베이컨 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '베이컨 추가',
    detailName: '베이컨 추가',
  },
  {
    ruleId: 'rule_topping_005',
    name: '추가토핑 - 올리브 추가',
    pattern: '올리브 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '올리브 추가',
    detailName: '올리브 추가',
  },
  {
    ruleId: 'rule_topping_006',
    name: '추가토핑 - 버섯 추가',
    pattern: '버섯 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '버섯 추가',
    detailName: '버섯 추가',
  },
  {
    ruleId: 'rule_topping_007',
    name: '추가토핑 - 양파 추가',
    pattern: '양파 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '양파 추가',
    detailName: '양파 추가',
  },
  {
    ruleId: 'rule_topping_008',
    name: '추가토핑 - 고구마무스 추가',
    pattern: '고구마무스 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '고구마무스 추가',
    detailName: '고구마무스 추가',
  },
  {
    ruleId: 'rule_topping_009',
    name: '추가토핑 - 피망 추가',
    pattern: '피망 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '피망 추가',
    detailName: '피망 추가',
  },
  {
    ruleId: 'rule_topping_010',
    name: '추가토핑 - 할라피뇨 추가',
    pattern: '할라피뇨 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '할라피뇨 추가',
    detailName: '할라피뇨 추가',
  },
  {
    ruleId: 'rule_topping_011',
    name: '추가토핑 - 브로콜리 추가',
    pattern: '브로콜리 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '브로콜리 추가',
    detailName: '브로콜리 추가',
  },
  {
    ruleId: 'rule_topping_012',
    name: '추가토핑 - 불고기 추가',
    pattern: '불고기 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '불고기 추가',
    detailName: '불고기 추가',
  },
  {
    ruleId: 'rule_topping_013',
    name: '추가토핑 - 컨츄리 치킨 추가',
    pattern: '컨츄리 치킨 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '컨츄리 치킨 추가',
    detailName: '컨츄리 치킨 추가',
  },
  {
    ruleId: 'rule_topping_014',
    name: '추가토핑 - 옥수수 추가',
    pattern: '옥수수 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '옥수수 추가',
    detailName: '옥수수 추가',
  },
  {
    ruleId: 'rule_topping_015',
    name: '추가토핑 - 세블락소시지 추가',
    pattern: '세블락소시지 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '세블락소시지 추가',
    detailName: '세블락소시지 추가',
  },
  {
    ruleId: 'rule_topping_016',
    name: '추가토핑 - 새우 추가',
    pattern: '새우 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '새우 추가',
    detailName: '새우 추가',
  },
  {
    ruleId: 'rule_topping_017',
    name: '추가토핑 - 웨지감자 추가',
    pattern: '웨지감자 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '웨지감자 추가',
    detailName: '웨지감자 추가',
  },
  {
    ruleId: 'rule_topping_018',
    name: '추가토핑 - 불갈비 추가',
    pattern: '불갈비 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '불갈비 추가',
    detailName: '불갈비 추가',
  },
  {
    ruleId: 'rule_topping_019',
    name: '추가토핑 - 마요네즈 추가',
    pattern: '마요네즈 추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '마요네즈 추가',
    detailName: '마요네즈 추가',
  },
  {
    ruleId: 'rule_topping_020',
    name: '추가토핑 - 마요네즈30g추가 (마요네즈 통합)',
    pattern: '마요네즈30g추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '마요네즈 추가',
    detailName: '마요네즈 추가',
  },
  {
    ruleId: 'rule_topping_021',
    name: '추가토핑 - 고구마90g추가 (고구마무스 통합)',
    pattern: '고구마90g추가',
    matchType: 'exact',
    category: '추가토핑',
    groupName: '고구마무스 추가',
    detailName: '고구마무스 추가',
  },

  // ============================================================
  // 음료 카테고리 (5개, BASIC_RULES rule_drink_001 "콜라" 별도)
  // 각 음료는 별도 그룹으로 표시
  // ============================================================
  {
    ruleId: 'rule_drink_002',
    name: '음료 - 사이다',
    pattern: '사이다',
    matchType: 'exact',
    category: '음료',
    groupName: '사이다',
    detailName: '사이다',
  },
  {
    ruleId: 'rule_drink_003',
    name: '음료 - 맥주',
    pattern: '맥주',
    matchType: 'exact',
    category: '음료',
    groupName: '맥주',
    detailName: '맥주',
  },
  {
    ruleId: 'rule_drink_004',
    name: '음료 - 소주',
    pattern: '소주',
    matchType: 'exact',
    category: '음료',
    groupName: '소주',
    detailName: '소주',
  },
  {
    ruleId: 'rule_drink_005',
    name: '음료 - 기타 음료',
    pattern: '기타 음료',
    matchType: 'exact',
    category: '음료',
    groupName: '기타 음료',
    detailName: '기타 음료',
  },
  {
    ruleId: 'rule_drink_006',
    name: '음료 - 기타 주류',
    pattern: '기타 주류',
    matchType: 'exact',
    category: '음료',
    groupName: '기타 주류',
    detailName: '기타 주류',
  },

  // ============================================================
  // 품목제외 카테고리 (20개)
  // status-classifier에서 category === '품목제외' 매칭 시 자동 excluded 처리
  // ============================================================
  {
    ruleId: 'rule_excluded_001',
    name: '품목제외 - 배달비',
    pattern: '배달비',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '배달비',
  },
  {
    ruleId: 'rule_excluded_002',
    name: '품목제외 - 추가 금액',
    pattern: '추가 금액',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '추가 금액',
  },
  {
    ruleId: 'rule_excluded_003',
    name: '품목제외 - 본사 권장 외 메뉴',
    pattern: '본사 권장 외 메뉴',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '본사 권장 외 메뉴',
  },
  {
    ruleId: 'rule_excluded_004',
    name: '품목제외 - 기타',
    pattern: '기타',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '기타',
  },
  {
    ruleId: 'rule_excluded_005',
    name: '품목제외 - 포장',
    pattern: '포장',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '포장',
  },
  {
    ruleId: 'rule_excluded_006',
    name: '품목제외 - 일회용품',
    pattern: '일회용품',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '일회용품',
  },
  {
    ruleId: 'rule_excluded_007',
    name: '품목제외 - 리뷰이벤트',
    pattern: '리뷰이벤트',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '리뷰이벤트',
  },
  {
    ruleId: 'rule_excluded_008',
    name: '품목제외 - 사장님 금액 할인',
    pattern: '사장님 금액 할인',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '사장님 금액 할인',
  },
  {
    ruleId: 'rule_excluded_009',
    name: '품목제외 - 쿠폰/할인',
    pattern: '쿠폰/할인',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '쿠폰/할인',
  },
  {
    ruleId: 'rule_excluded_010',
    name: '품목제외 - 갈릭디핑/핫소스 포함',
    pattern: '갈릭디핑/핫소스 포함',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '갈릭디핑/핫소스 포함',
  },
  {
    ruleId: 'rule_excluded_011',
    name: '품목제외 - 스파게티 사이즈업',
    pattern: '스파게티 사이즈업',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '스파게티 사이즈업',
  },
  {
    ruleId: 'rule_excluded_012',
    name: '품목제외 - 피클/갈릭디핑소스/핫소스 제외',
    pattern: '피클/갈릭디핑소스/핫소스 제외',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '피클/갈릭디핑소스/핫소스 제외',
  },
  {
    ruleId: 'rule_excluded_013',
    name: '품목제외 - 갈릭디핑/핫소스 제외',
    pattern: '갈릭디핑/핫소스 제외',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '갈릭디핑/핫소스 제외',
  },
  {
    ruleId: 'rule_excluded_014',
    name: '품목제외 - 피클 제외',
    pattern: '피클 제외',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '피클 제외',
  },
  {
    ruleId: 'rule_excluded_015',
    name: '품목제외 - 핫소스 제외',
    pattern: '핫소스 제외',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '핫소스 제외',
  },
  {
    ruleId: 'rule_excluded_016',
    name: '품목제외 - 갈릭디핑소스 제외',
    pattern: '갈릭디핑소스 제외',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '갈릭디핑소스 제외',
  },
  {
    ruleId: 'rule_excluded_017',
    name: '품목제외 - 피클/갈릭디핑소스/핫소스 포함',
    pattern: '피클/갈릭디핑소스 포함',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '피클/갈릭디핑소스 포함',
  },
  {
    ruleId: 'rule_excluded_018',
    name: '품목제외 - 파마산 제외',
    pattern: '파마산 제외',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '파마산 제외',
  },
  {
    ruleId: 'rule_excluded_019',
    name: '품목제외 - 피클/핫소스 제외',
    pattern: '피클/핫소스 제외',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '피클/핫소스 제외',
  },
  {
    ruleId: 'rule_excluded_020',
    name: '품목제외 - 피클/갈릭디핑소스/핫소스 포함',
    pattern: '피클/갈릭디핑소스/핫소스 포함',
    matchType: 'exact',
    category: '품목제외',
    groupName: '품목제외',
    detailName: '피클/갈릭디핑소스/핫소스 포함',
  },
];
